// <auto-generated />
using System;
using CinemaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaWeb.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260419082132_TaoBangCombo")]
    partial class TaoBangCombo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("CinemaWeb.Models.ComboBapNuoc", b =>
                {
                    b.Property<int>("MaCombo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Gia")
                        .HasColumnType("REAL");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenCombo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaCombo");

                    b.ToTable("ComboBapNuocs");
                });

            modelBuilder.Entity("CinemaWeb.Models.Ghe", b =>
                {
                    b.Property<int>("MaGhe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaGhe");

                    b.ToTable("Ghes");

                    b.HasData(
                        new
                        {
                            MaGhe = 1,
                            TenGhe = "A1",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 2,
                            TenGhe = "A2",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 3,
                            TenGhe = "A3",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 4,
                            TenGhe = "A4",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 5,
                            TenGhe = "A5",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 6,
                            TenGhe = "A6",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 7,
                            TenGhe = "A7",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 8,
                            TenGhe = "A8",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 9,
                            TenGhe = "A9",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 10,
                            TenGhe = "A10",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 11,
                            TenGhe = "A11",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 12,
                            TenGhe = "A12",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 13,
                            TenGhe = "A13",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 14,
                            TenGhe = "A14",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 15,
                            TenGhe = "A15",
                            TrangThai = "Trong"
                        },
                        new
                        {
                            MaGhe = 16,
                            TenGhe = "A16",
                            TrangThai = "Trong"
                        });
                });

            modelBuilder.Entity("CinemaWeb.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("CinemaWeb.Models.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhim");

                    b.ToTable("Phims");
                });

            modelBuilder.Entity("CinemaWeb.Models.SuatChieu", b =>
                {
                    b.Property<int>("MaSuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhimId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSuat");

                    b.HasIndex("PhimId");

                    b.ToTable("SuatChieus");
                });

            modelBuilder.Entity("CinemaWeb.Models.Ve", b =>
                {
                    b.Property<int>("MaVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BapNuoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DanhSachGhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GheId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaPhim")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuatChieuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenGhe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TongTien")
                        .HasColumnType("REAL");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaVe");

                    b.ToTable("Ves");
                });

            modelBuilder.Entity("CinemaWeb.Models.SuatChieu", b =>
                {
                    b.HasOne("CinemaWeb.Models.Phim", "Phim")
                        .WithMany()
                        .HasForeignKey("PhimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");
                });
#pragma warning restore 612, 618
        }
    }
}
